name: app

type: php:8.1

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - iconv
        - dom
        - simplexml
        - exif
        - opcache
        - imagick
        - fileinfo
        - sodium
        - redis

variables:
    php:
        memory_limit: 128M
        opcache.preload: config/preload.php
    env:
        APP_ENV: "prod"

build:
    flavor: none

disk: 2048

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var":
        source: "local"
        source_path: "var"
    "/public/var":
        source: "local"
        source_path: "public_var"
    "/public/pimcore":
        source: "local"
        source_path: "public_pimcore"
    "/public/bundles":
        source: "local"
        source_path: "public_bundles"

relationships:
    database: "db:mysql"
    redis: "cache:redis"

hooks:
    build: |
        set -e

        curl -fsS https://raw.githubusercontent.com/platformsh/snippets/main/src/install-phpredis.sh | { bash /dev/fd/3 5.1.1 ; } 3<&0
        curl -sS https://platform.sh/cli/installer | php

        composer install --no-ansi --no-progress --prefer-dist --no-scripts
    deploy: |
        set -e

        if [ ! -f public/var/.platform.installed ]; then
            ./installer.sh
            touch public/var/.platform.installed
        fi

        ./bin/console cache:clear

crons:
    pimcore_maintenance:
        spec: "*/5 * * * *"
        commands:
            start: "bin/console pimcore:maintenance --async"
    messenger_consume:
        spec: "*/5 * * * *"
        commands:
            start: "bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize --time-limit=300"

source:
    operations:
        auto-update:
            command: |
                curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
